import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useMemo, useState } from 'react';
import { SupportCase } from '@/components/support-case';
import { Activity, ArrowDownToLine, ArrowRight, CheckCircle2, ClipboardList, Clock3, RefreshCw, Search, ShieldAlert, Users, X } from 'lucide-react';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid, Line, LineChart } from 'recharts';
import { Button } from '@/components/ui/button';
import { AppShell } from '@/components/app-shell';
import { isSchool50, getResults, riskBucket, valueText, type Result } from '@/lib/safeschool';
import { useLanguage } from '@/lib/use-language';
export const Route=createFileRoute('/dashboard/$role')({head:({params})=>({meta:[{title:`${params.role} dashboard | SafeSchool AI`},{name:'description',content:'SafeSchool AI сауалнама нәтижелері мен оқушы қауіп деңгейлері.'},{property:'og:title',content:`${params.role} dashboard | SafeSchool AI`},{property:'og:description',content:'SafeSchool AI сауалнама нәтижелері мен оқушы қауіп деңгейлері.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:Dashboard});
const dateOf=(r:Result)=>{const v=r.created_at??r.date??r.submitted_at??r.timestamp; if(!v)return '';const d=new Date(String(v));return Number.isNaN(d.getTime())?'':d.toLocaleDateString()};
const csvCell=(v:unknown)=>`"${valueText(v).replaceAll('"','""')}"`;
function Dashboard(){const {role}=Route.useParams();const valid=role==='admin'||role==='teacher'||role==='psychologist';const r=valid?role:'admin';const {t,lang}=useLanguage();const [results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[level,setLevel]=useState('all'),[selected,setSelected]=useState<Result|null>(null);const load=async()=>{setLoading(true);setError('');try{setResults(await getResults(r))}catch{setError(t.apiError)}finally{setLoading(false)}};useEffect(()=>{void load()},[r]);
 const scoped=useMemo(()=>results.filter(x=>isSchool50(x.school)&&(r==='admin'||!localStorage.getItem(`${r}Class`)||x.class_name===localStorage.getItem(`${r}Class`))),[results,r]);
 const filtered=useMemo(()=>scoped.filter(x=>(level==='all'||riskBucket(x.risk_level)===level)&&(!query||[x.student_id,x.school,x.class_name].some(v=>String(v??'').toLowerCase().includes(query.toLowerCase())))),[scoped,level,query]);
 const counts={high:scoped.filter(x=>riskBucket(x.risk_level)==='high').length,medium:scoped.filter(x=>riskBucket(x.risk_level)==='medium').length,low:scoped.filter(x=>riskBucket(x.risk_level)==='low').length};const colors=['var(--chart-high)','var(--chart-medium)','var(--chart-low)'];const chart=[{name:t.high,value:counts.high},{name:t.medium,value:counts.medium},{name:t.low,value:counts.low}].filter(x=>x.value>0);
 const exportCsv=()=>{const rows=[['student_id','school','class_name','final_result','risk_level','risk_score','date'],...filtered.map(x=>[x.student_id,x.school,x.class_name,x.final_result,x.risk_level,x.risk_score,dateOf(x)])];const csv='\uFEFF'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`safeschool-${r}-results.csv`;a.click();URL.revokeObjectURL(url)};
 return <AppShell role={r} title={`${t[r]} · ${t.dashboard}`} subtitle={t.dashSub} back={`/login/${r}`}><div className="dashboard-actions"><span className="data-source"><span/>{loading?t.loading:error?t.apiError:`${scoped.length} ${t.records}`}</span><div><Button variant="outline" onClick={exportCsv} disabled={!filtered.length}><ArrowDownToLine size={16}/>{t.export}</Button><Button onClick={()=>void load()} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{t.refresh}</Button></div></div>{error&&<div className="inline-alert" role="alert">{error} <Button variant="outline" size="sm" onClick={()=>void load()}>{t.refresh}</Button></div>}
 <div className="stats-grid">{[{label:t.total,value:scoped.length,icon:ClipboardList,style:'total'},{label:t.high,value:counts.high,icon:ShieldAlert,style:'high'},{label:t.medium,value:counts.medium,icon:Activity,style:'medium'},{label:t.low,value:counts.low,icon:CheckCircle2,style:'low'}].map(({label,value,icon:Icon,style})=><div className="stat-card" key={style}><div className="stat-top"><span className={`stat-icon ${style}`}><Icon size={20}/></span><span className="stat-mini">{style==='total'?'01':style==='high'?'02':style==='medium'?'03':'04'}</span></div><div className="stat-value">{loading?'—':value}</div><div className="stat-label">{label}</div></div>)}</div>
 <div className="dashboard-middle"><div className="chart-panel"><div className="panel-heading"><div><p className="eyebrow">ANALYTICS</p><h2>{t.distribution}</h2></div><span className="chart-period">{scoped.length} {t.records}</span></div>{chart.length?<div className="chart-content"><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chart} dataKey="value" innerRadius={68} outerRadius={92} paddingAngle={3} stroke="none">{chart.map((x,i)=><Cell key={x.name} fill={colors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{scoped.length}</strong><small>{t.total}</small></div></div><div className="chart-legend">{chart.map(x=><div key={x.name}><span className={`legend-dot ${riskBucket(x.name)==='unknown'?(x.name===t.high?'high':x.name===t.medium?'medium':'low'):riskBucket(x.name)}`}/><span>{x.name}</span><strong>{x.value}</strong></div>)}</div></div>:<div className="empty-chart">{loading?t.loading:t.noResults}</div>}</div><div className="insight-panel"><span className="insight-icon"><Users size={24}/></span><p className="eyebrow">SAFESCHOOL AI</p><h2>{t.work}</h2><p>{t.workSub}</p><div className="insight-count"><strong>{counts.high+counts.medium}</strong><span>{t.high} / {t.medium}</span></div><a href="#work-panel" className="insight-link">{t.work}<ArrowRight size={17}/></a></div></div>
 <section className="results-section"><div className="section-heading"><div><p className="eyebrow">RECORDS</p><h2>{t.results}</h2></div><span className="section-count">{filtered.length} {t.records}</span></div><div className="table-panel"><div className="table-tools"><div className="search-box"><Search size={18}/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<Button variant="ghost" size="icon" aria-label="Clear" onClick={()=>setQuery('')}><X size={16}/></Button>}</div><select aria-label={t.filter} value={level} onChange={e=>setLevel(e.target.value)}><option value="all">{t.all}</option><option value="high">{t.high}</option><option value="medium">{t.medium}</option><option value="low">{t.low}</option></select></div><div className="table-scroll"><table><thead><tr><th>{t.id}</th><th>{t.school}</th><th>{t.class}</th><th>{t.result}</th><th>{t.risk}</th><th>{t.score}</th><th>{t.date}</th><th></th></tr></thead><tbody>{filtered.map((x,i)=><tr key={`${x.student_id}-${i}`} className={selected===x?'row-selected':''} onClick={()=>{setSelected(x);setTimeout(()=>document.getElementById('work-panel')?.scrollIntoView({behavior:'smooth'}),50)}}><td className="student-id">{valueText(x.student_id)}</td><td>{valueText(x.school)}</td><td>{valueText(x.class_name)}</td><td>{valueText(x.final_result)}</td><td><span className={`risk-pill ${riskBucket(x.risk_level)}`}>{valueText(x.risk_level)}</span></td><td>{valueText(x.risk_score)}</td><td>{dateOf(x)||'—'}</td><td><ArrowRight size={16}/></td></tr>)}</tbody></table>{!loading&&!filtered.length&&<div className="table-empty">{t.noResults}</div>}</div></div></section>
 <SupportCase selected={selected} results={scoped} lang={lang} role={r} onClear={()=>setSelected(null)}/></AppShell>}
