import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, QrCode, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AppShell } from '@/components/app-shell';
import { classes, SCHOOL, type Role } from '@/lib/safeschool';
import { useLanguage } from '@/lib/use-language';
export const Route=createFileRoute('/login/$role')({head:({params})=>({meta:[{title:`${params.role} | SafeSchool AI`},{name:'description',content:'SafeSchool AI жүйесіне кіру.'},{property:'og:title',content:`${params.role} | SafeSchool AI`},{property:'og:description',content:'SafeSchool AI жүйесіне кіру.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:Login});
function Login(){const {role}=Route.useParams();const valid=(['student','teacher','psychologist','admin'] as string[]).includes(role);const r=(valid?role:'student') as Role;const {lang,t}=useLanguage();const navigate=useNavigate();const [id,setId]=useState(''),[password,setPassword]=useState(''),[school,setSchool]=useState(''),[cls,setCls]=useState(''),[error,setError]=useState(''),[show,setShow]=useState(false);
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!id.trim()||!password.trim()||(r!=='admin'&&(!cls))){setError(t.fill);return}if(r==='admin'&&(id.trim()!=='admin'||password.trim()!=='1234')){setError(t.incorrect);return} if(r==='student'){localStorage.setItem('studentId',id.trim());localStorage.setItem('studentSchool',SCHOOL);localStorage.setItem('studentClass',cls);void navigate({to:'/survey'});}else{localStorage.setItem(`${r}School`,SCHOOL);localStorage.setItem(`${r}Class`,cls);void navigate({to:'/dashboard/$role',params:{role:r}})}};
 const qrUrl=typeof window!=='undefined'?`${window.location.origin}/login/student`:'';
 return <AppShell role={r} title={`${t[r]} · ${t.login}`} subtitle={t.welcomeSub} back="/"><div className="login-layout"><div className="login-card"><div className="login-icon"><LockKeyhole size={24}/></div><h2>{t.login}</h2><p className="login-lead">{t[r]} · SafeSchool AI</p><form onSubmit={submit} className="form-stack">{r!=='admin'&&<><label>{t.school}<input value={SCHOOL} readOnly aria-label={t.school}/></label><label>{t.class}<select value={cls} onChange={e=>setCls(e.target.value)} required><option value="">{t.choose}</option>{classes[lang].map(x=><option key={x} value={x}>{x}</option>)}</select></label></>}<label>{r==='admin'?t.user:t.id}<input value={id} onChange={e=>setId(e.target.value)} placeholder={r==='admin'?'admin':r==='student'?'ST001':r==='teacher'?'TCH001':'PSY001'} autoComplete="username" required/></label><label>{t.password}<span className="password-wrap"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><Button type="button" variant="ghost" size="icon" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</Button></span></label>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" size="lg" className="form-submit">{t.enter}<ArrowRight size={17}/></Button></form></div><div className="login-side"><div className="side-shield"><ShieldCheck size={30}/></div><p className="eyebrow">SAFESCHOOL AI</p><h2>{t.welcome}</h2><p>{t.welcomeSub}</p>{r==='student'&&<div className="qr-panel"><div><QrCode size={20}/><strong>{t.qr}</strong><p>{t.qrSub}</p></div><img src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(qrUrl)}`} alt={t.qr}/></div>}<Link to="/" className="side-link">{t.home}<ArrowRight size={16}/></Link></div></div></AppShell>}
