import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ArrowRight, CheckCircle2, ClipboardList, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AppShell } from '@/components/app-shell';
import { SCHOOL, questions, sendSurvey, valueText } from '@/lib/safeschool';
import { useLanguage } from '@/lib/use-language';
export const Route=createFileRoute('/survey')({head:()=>({meta:[{title:'Оқушы сауалнамасы | SafeSchool AI'},{name:'description',content:'Оқушылардың цифрлық қауіпсіздік сауалнамасы.'},{property:'og:title',content:'Оқушы сауалнамасы | SafeSchool AI'},{property:'og:description',content:'Оқушылардың цифрлық қауіпсіздік сауалнамасы.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:Survey});
function Survey(){const {lang,t}=useLanguage();const [identity,setIdentity]=useState({id:'',school:'',cls:''});const [answers,setAnswers]=useState<number[]>(Array(30).fill(0));const [complaint,setComplaint]=useState('');const [sending,setSending]=useState(false);const [result,setResult]=useState<Record<string,unknown>|null>(null);const [error,setError]=useState('');useEffect(()=>{setIdentity({id:localStorage.getItem('studentId')||'',school:SCHOOL,cls:localStorage.getItem('studentClass')||''})},[]);
 const submit=async()=>{if(!identity.id||!identity.school||!identity.cls){setError(t.fill);return}setSending(true);setError('');try{const mapped=Object.fromEntries(answers.map((v,i)=>[`q${i+1}`,v]));const data=await sendSurvey({school:SCHOOL,class_name:identity.cls,student_class:identity.cls,student_id:identity.id,year:new Date().getFullYear(),text:complaint,complaint_text:complaint,answers:JSON.stringify(mapped)});setResult(data)}catch(e){setError(e instanceof Error?e.message:t.apiError)}finally{setSending(false)}};
 return <AppShell role="student" title={t.surveyTitle} subtitle={t.surveySub} back="/login/student"><div className="survey-layout"><div className="survey-main"><div className="survey-intro"><span className="survey-intro-icon"><ClipboardList size={23}/></span><div><strong>{t.surveyTitle}</strong><p>{questions[lang].length} {t.number.toLowerCase()} · SafeSchool AI</p></div></div>{!identity.id&&<div className="inline-alert"><Link to="/login/$role" params={{role:'student'}}>{t.login}<ArrowRight size={15}/></Link></div>}<div className="question-list">{questions[lang].map((q,i)=><div className="survey-question" key={i}><span className="question-number">{String(i+1).padStart(2,'0')}</span><div className="question-body"><p>{q}</p><div className="answer-options">{([0,1,2] as const).map(v=><label key={v} className={answers[i]===v?'selected':''}><input type="radio" name={`q${i}`} checked={answers[i]===v} onChange={()=>setAnswers(a=>a.map((x,j)=>j===i?v:x))}/><span>{v===0?t.no:v===1?t.sometimes:t.yes}</span></label>)}</div></div></div>)}</div><div className="complaint-box"><label htmlFor="complaint">{t.complaint}</label><textarea id="complaint" value={complaint} onChange={e=>setComplaint(e.target.value)} rows={4}/></div>{error&&<p className="form-error" role="alert">{error}</p>}{result&&<div className="success-box" role="status"><CheckCircle2 size={23}/><div><strong>{t.saved}</strong><p>{t.risk}: {valueText(result['risk_level'])} · {t.score}: {valueText(result['risk_score'])}</p><p>{t.result}: {valueText(result['final_result']||result['result'])}</p></div></div>}<Button size="lg" onClick={submit} disabled={sending} className="survey-submit">{sending?t.sending:t.submit}<ArrowRight size={17}/></Button></div><aside className="survey-aside"><div className="aside-card"><span className="aside-icon"><ShieldCheck size={23}/></span><h3>{t.secure}</h3><dl><dt>{t.school}</dt><dd>{identity.school||'—'}</dd><dt>{t.class}</dt><dd>{identity.cls||'—'}</dd><dt>{t.id}</dt><dd>{identity.id||'—'}</dd></dl></div><div className="aside-progress"><span>{t.survey}</span><strong>{questions[lang].length} / {questions[lang].length}</strong><div className="progress-track"><span/></div></div></aside></div></AppShell>}
