import { useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, ArrowRight, ArrowUpRight, CheckCircle2, Clock3, Plus, ShieldAlert, X } from 'lucide-react';
import { Link } from '@tanstack/react-router';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { SCHOOL, riskBucket, valueText, type Lang, type Result } from '@/lib/safeschool';
import { caseCopy, readActions, writeAction, type ActionType, type CaseStatus, type SupportAction } from '@/lib/support-case';

const dateOf=(r:Result)=>{const raw=r.created_at??r.date??r.submitted_at??r.timestamp;const d=raw?new Date(String(raw)):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleDateString():''};
const timeOf=(r:Result)=>{const raw=r.created_at??r.date??r.submitted_at??r.timestamp;return raw?new Date(String(raw)).getTime()||0:0};
const stageTypes:ActionType[]=['psychologist','teacher','follow_up','current'];
const statuses:CaseStatus[]=['in_progress','monitoring','stabilized','needs_support'];
const score=(r:Result)=>{const n=Number(r.risk_score);return Number.isFinite(n)?n:null};
export function SupportCase({selected,results,lang,role,onClear}:{selected:Result|null;results:Result[];lang:Lang;role:'admin'|'teacher'|'psychologist';onClear:()=>void}) {
 const t=caseCopy[lang];
 const [actions,setActions]=useState<SupportAction[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[userId,setUserId]=useState<string|null>(null),[authorized,setAuthorized]=useState(false),[authBusy,setAuthBusy]=useState(false),[message,setMessage]=useState('');
 const [form,setForm]=useState({action_date:new Date().toISOString().slice(0,10),action_type:'psychologist' as ActionType,specialist:'',note:'',next_review_date:'',status:'in_progress' as CaseStatus});
 const history=useMemo(()=>selected?results.filter(x=>x.student_id&&String(x.student_id).trim().toLowerCase()===String(selected.student_id).trim().toLowerCase()).sort((a,b)=>timeOf(a)-timeOf(b)):[],[selected,results]);
 const first=history[0],last=history[history.length-1];const before=first?score(first):null,after=last?score(last):null;
 const change=history.length>1&&before!==null&&after!==null?after-before:null;
 useEffect(()=>{let active=true;const sync=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!active)return;setUserId(user?.id??null);if(user){const {data}=await supabase.from('user_roles').select('role').eq('user_id',user.id);if(active)setAuthorized(Boolean(data?.some(x=>x.role===role||x.role==='admin')))}else setAuthorized(false)};void sync();const {data:{subscription}}=supabase.auth.onAuthStateChange(()=>{void sync()});return()=>{active=false;subscription.unsubscribe()}},[role]);
 useEffect(()=>{let active=true;setActions([]);setError('');setMessage('');setOpen(false);if(selected?.student_id&&userId&&authorized){setLoading(true);void readActions(String(selected.student_id)).then(rows=>{if(active)setActions(rows)}).catch(()=>{if(active)setError(t.saveError)}).finally(()=>{if(active)setLoading(false)})}return()=>{active=false}},[selected?.student_id,userId,authorized,t.saveError]);
 const signIn=async(e:React.FormEvent)=>{e.preventDefault();setAuthBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setPassword('');setAuthBusy(false)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!selected?.student_id||!authorized||!userId)return;setSaving(true);setError('');try{await writeAction({...form,student_id:String(selected.student_id),school:SCHOOL,class_name:String(selected.class_name??''),next_review_date:form.next_review_date||null});setActions(await readActions(String(selected.student_id)));setOpen(false);setMessage(t.recorded);setForm({action_date:new Date().toISOString().slice(0,10),action_type:'psychologist',specialist:'',note:'',next_review_date:'',status:'in_progress'})}catch{setError(t.saveError)}finally{setSaving(false)}};
 const latest=actions[actions.length-1];
 return <section id="work-panel" className="work-section"><div className="section-heading"><div><p className="eyebrow">STUDENT SUPPORT CASE</p><h2>{lang==='kk'?'Оқушымен жүргізілген жұмыс':lang==='ru'?'Работа с учеником':'Student support case'}</h2></div><div className="support-heading-actions">{selected&&authorized&&<Button onClick={()=>setOpen(true)}><Plus size={16}/>{t.add}</Button>}{selected&&<Button variant="ghost" size="icon" aria-label={t.cancel} onClick={onClear}><X size={17}/></Button>}</div></div>
 {!selected?<div className="work-empty"><span><ShieldAlert size={26}/></span><p>{lang==='kk'?'Нәтижелер кестесінен оқушыны таңдаңыз':lang==='ru'?'Выберите ученика из таблицы результатов':'Select a student in the results table'}</p></div>:<div className="case-layout"><aside className="case-profile"><div className="selected-student"><span className="selected-avatar">{String(selected.student_id||'S').slice(0,2).toUpperCase()}</span><div><strong>{valueText(selected.student_id)}</strong><small>{SCHOOL} · {valueText(selected.class_name)}</small></div></div><dl className="case-facts"><dt>{lang==='kk'?'Мектеп':lang==='ru'?'Школа':'School'}</dt><dd>{SCHOOL}</dd><dt>{lang==='kk'?'Сынып':lang==='ru'?'Класс':'Class'}</dt><dd>{valueText(selected.class_name)}</dd><dt>{t.initial}</dt><dd>{valueText(first?.risk_level??selected.risk_level)} · {valueText(first?.risk_score??selected.risk_score)}</dd><dt>{t.status}</dt><dd>{latest?t.statuses[latest.status]:t.noTrend}</dd></dl></aside><div className="case-main"><div className="case-trend"><div className="case-title"><p className="eyebrow">{t.dynamics}</p><h3>{t.dynamics}</h3></div><div className="score-flow">{history.filter(x=>score(x)!==null).map((x,i)=><div className="score-step" key={`${timeOf(x)}-${i}`}><div className={`score-tile ${riskBucket(x.risk_level)}`}><small>{dateOf(x)||t.noDate}</small><strong>{score(x)}</strong><span>{valueText(x.risk_level)}</span></div>{i<history.filter(y=>score(y)!==null).length-1&&<ArrowRight size={17}/>}</div>)}{history.every(x=>score(x)===null)&&<p>{t.noTrend}</p>}</div><div className={`trend-change ${change===null?'neutral':change>0?'worse':'better'}`}>{change===null?<Clock3 size={23}/>:change>0?<ArrowUpRight size={23}/>:<ArrowDownRight size={23}/>}<div><strong>{change===null?'—':`${change>0?'+':''}${change}`}</strong><span>{change===null?t.noTrend:change>0?t.increased:change<0?t.decreased:t.unchanged}</span></div></div></div>
 <div className="case-section-title"><h3>{t.stages}</h3></div><div className="case-stages"><div className="case-stage"><span className="stage-mark detected"><ShieldAlert size={18}/></span><strong>{lang==='kk'?'Қауіп анықталды':lang==='ru'?'Риск выявлен':'Risk detected'}</strong><small>{first?dateOf(first)||t.noDate:'—'}</small></div>{stageTypes.map(type=>{const record=actions.filter(a=>a.action_type===type).at(-1);return <div className="case-stage" key={type}><span className={`stage-mark ${record?'done':''}`}>{record?<CheckCircle2 size={18}/>:<Clock3 size={18}/>}</span><strong>{t.types[type]}</strong><small>{record?record.action_date:'—'}</small></div>})}</div>
 <div className="case-section-title"><h3>{t.actions}</h3><span>{actions.length} {lang==='kk'?'жазба':lang==='ru'?'записей':'records'}</span></div>{!userId?<div className="case-auth"><p>{t.loginHint}</p><form onSubmit={signIn}><label>{t.email}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>{t.password}<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><Button disabled={authBusy} type="submit">{t.signIn}</Button></form></div>:!authorized?<div className="case-auth"><p>{t.accessDenied}</p><Button variant="outline" onClick={()=>void supabase.auth.signOut()}>{t.signOut}</Button></div>:<><div className="case-history">{loading?<p className="case-empty">{lang==='kk'?'Жүктелуде…':lang==='ru'?'Загрузка…':'Loading…'}</p>:!actions.length?<p className="case-empty">{t.empty}</p>:actions.map((a,i)=><div className="case-history-row" key={a.id}><span className="history-num">{String(i+1).padStart(2,'0')}</span><div><strong>{t.types[a.action_type]}</strong><small>{a.action_date} · {a.specialist}</small><p>{a.note}</p><small>{t.nextReview}: {a.next_review_date||'—'}</small></div><span className={`case-status ${a.status}`}>{t.statuses[a.status]}</span></div>)}</div><Button variant="outline" size="sm" onClick={()=>void supabase.auth.signOut()}>{t.signOut}</Button></>}
 {message&&<p role="status" className="case-feedback">{message}</p>}{error&&<p role="alert" className="form-error">{error}</p>}
 <Link to="/login/$role" params={{role:'student'}} className="history-link">{t.types.follow_up}<ArrowRight size={16}/></Link></div></div>}
 {open&&selected&&<div className="case-modal-backdrop" onClick={()=>setOpen(false)}><div className="case-modal" role="dialog" aria-modal="true" aria-labelledby="case-form-title" onClick={e=>e.stopPropagation()}><div className="case-modal-heading"><h2 id="case-form-title">{t.add}</h2><Button variant="ghost" size="icon" aria-label={t.cancel} onClick={()=>setOpen(false)}><X size={18}/></Button></div><form className="case-form" onSubmit={save}><label>{t.actionDate}<input type="date" required value={form.action_date} onChange={e=>setForm({...form,action_date:e.target.value})}/></label><label>{t.type}<select value={form.action_type} onChange={e=>setForm({...form,action_type:e.target.value as ActionType})}>{stageTypes.map(type=><option key={type} value={type}>{t.types[type]}</option>)}</select></label><label>{t.specialist}<input required maxLength={120} value={form.specialist} onChange={e=>setForm({...form,specialist:e.target.value})}/></label><label>{t.nextReview}<input type="date" value={form.next_review_date} onChange={e=>setForm({...form,next_review_date:e.target.value})}/></label><label className="case-form-wide">{t.note}<textarea required maxLength={500} rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><label className="case-form-wide">{t.status}<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as CaseStatus})}>{statuses.map(s=><option key={s} value={s}>{t.statuses[s]}</option>)}</select></label><div className="case-form-actions"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>{t.cancel}</Button><Button type="submit" disabled={saving}>{t.save}</Button></div>{error&&<p role="alert" className="form-error">{error}</p>}</form></div></div>}
 </section>
}
