import original from './legacy-data.json';

export type Lang = 'kk' | 'ru' | 'en';
export type Role = 'student' | 'teacher' | 'psychologist' | 'admin';
export type Result = Record<string, unknown> & { student_id?: string; school?: string; class_name?: string; risk_level?: string; risk_score?: number; final_result?: string; created_at?: string; date?: string; submitted_at?: string; timestamp?: string };
export const API_URL = 'https://safeschool-ai.onrender.com';
export const questions = original.questionsByLang;
export const SCHOOL = '№50 КЕЛЕШЕК жалпы білім беретін орта мектеп';
export const isSchool50 = (v: unknown) => { const x = String(v ?? '').toLowerCase(); return x === SCHOOL.toLowerCase() || /(№|no\.?\s*)50(\D|$)/.test(x); };
export const schools = original.schoolTranslations;
export const classes = original.classTranslations;
export const endpoint: Record<Exclude<Role,'student'>, string> = { admin: 'admin_results', teacher: 'teacher_results', psychologist: 'psychologist_results' };
export async function getResults(role: Exclude<Role,'student'>): Promise<Result[]> {
  const res = await fetch(`${API_URL}/${endpoint[role]}`);
  if (!res.ok) throw new Error(`API ${res.status}`);
  const data: unknown = await res.json();
  if (!data || typeof data !== 'object' || !('results' in data) || !Array.isArray(data.results)) throw new Error('Invalid results response');
  return data.results as Result[];
}
export async function sendSurvey(data: { school:string; class_name:string; student_class:string; student_id:string; year:number; text:string; complaint_text:string; answers:string }) {
  const res = await fetch(`${API_URL}/submit_survey`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({...data,school:SCHOOL}) });
  const text = await res.text();
  if (!res.ok) throw new Error(`API ${res.status}: ${text}`);
  try { return JSON.parse(text) as Record<string, unknown>; } catch { return { final_result:text }; }
}
export const copy = {
 kk: { home:'Басты бет', overview:'Шолу', survey:'Сауалнама', admin:'Әкімші', teacher:'Мұғалім', psychologist:'Психолог', student:'Оқушы', welcome:'Қауіпсіз мектеп — сенімді болашақ', welcomeSub:'Оқушылардың цифрлық қауіпсіздігін бақылау және қолдау кеңістігі.', selectRole:'Панельге өту', login:'Кіру', enter:'Жалғастыру', school:'Мектеп', class:'Сынып', id:'ID', password:'Құпия сөз', user:'Логин', choose:'Таңдаңыз', fill:'Барлық өрісті толтырыңыз', incorrect:'Логин немесе құпия сөз қате', surveyTitle:'Цифрлық қауіпсіздік сауалнамасы', surveySub:'Жауаптарыңыз мұқият қаралады. Әр сұраққа өз тәжірибеңізге сай жауап беріңіз.', complaint:'Қосымша айтқыңыз келетін нәрсе', no:'Жоқ', sometimes:'Кейде', yes:'Иә', submit:'Жауаптарды жіберу', sending:'Жіберілуде…', saved:'Жауаптар сақталды', result:'Қорытынды', risk:'Қауіп деңгейі', score:'Қауіп баллы', dashboard:'Бақылау панелі', dashSub:'Оқушылардың қауіпсіздік көрсеткіштері', refresh:'Жаңарту', total:'Барлық сауалнамалар', high:'Жоғары қауіп', medium:'Орта қауіп', low:'Төмен қауіп', distribution:'Қауіп деңгейлері', results:'Сауалнама нәтижелері', search:'Оқушы ID немесе мектеп бойынша іздеу', all:'Барлық деңгейлер', date:'Күні', status:'Жағдайы', noResults:'Нәтиже табылмады', apiError:'Деректерді жүктеу мүмкін болмады. Кейінірек қайталап көріңіз.', work:'Оқушымен жүргізілген жұмыс', workSub:'Оқушыны таңдап, жұмыстың кезеңдерін қараңыз', selectStudent:'Нәтижелер кестесінен оқушыны таңдаңыз', detected:'Қауіп анықталды', psychWork:'Психолог жұмысы', teacherWork:'Сынып жетекшісі жұмысы', followUp:'Қайта бақылау', current:'Қазіргі жағдайы', pending:'Дерек жоқ', specialist:'Жауапты маман', note:'Ескертпе', history:'Оқушы динамикасы', historyEmpty:'Бұл оқушы бойынша бірнеше күнгі дерек әлі жоқ', retry:'Қайта сауалнама', export:'CSV жүктеу', filter:'Сүзгі', qr:'Оқушыға арналған QR', qrSub:'Бұл код оқушының кіру бетін ашады.', back:'Артқа', records:'жазба', showAll:'Барлығын көрсету', number:'Сұрақ', secure:'Қауіпсіз орта', loading:'Жүктелуде…', noteUnavailable:'Маман әрекеттерін сақтау үшін API қолдауы қажет.' },
 ru: { home:'Главная', overview:'Обзор', survey:'Анкета', admin:'Администратор', teacher:'Учитель', psychologist:'Психолог', student:'Ученик', welcome:'Безопасная школа — уверенное будущее', welcomeSub:'Пространство для мониторинга и поддержки цифровой безопасности учащихся.', selectRole:'Открыть панель', login:'Вход', enter:'Продолжить', school:'Школа', class:'Класс', id:'ID', password:'Пароль', user:'Логин', choose:'Выберите', fill:'Заполните все поля', incorrect:'Неверный логин или пароль', surveyTitle:'Анкета цифровой безопасности', surveySub:'Ваши ответы будут внимательно рассмотрены. Отвечайте исходя из своего опыта.', complaint:'Хотите добавить что-нибудь ещё?', no:'Нет', sometimes:'Иногда', yes:'Да', submit:'Отправить ответы', sending:'Отправка…', saved:'Ответы сохранены', result:'Результат', risk:'Уровень риска', score:'Балл риска', dashboard:'Панель мониторинга', dashSub:'Показатели безопасности учащихся', refresh:'Обновить', total:'Всего анкет', high:'Высокий риск', medium:'Средний риск', low:'Низкий риск', distribution:'Уровни риска', results:'Результаты анкет', search:'Поиск по ID ученика или школе', all:'Все уровни', date:'Дата', status:'Состояние', noResults:'Результаты не найдены', apiError:'Не удалось загрузить данные. Попробуйте позже.', work:'Работа с учеником', workSub:'Выберите ученика, чтобы просмотреть этапы работы', selectStudent:'Выберите ученика из таблицы результатов', detected:'Риск выявлен', psychWork:'Работа психолога', teacherWork:'Работа классного руководителя', followUp:'Повторное наблюдение', current:'Текущее состояние', pending:'Нет данных', specialist:'Ответственный специалист', note:'Примечание', history:'Динамика ученика', historyEmpty:'Пока нет данных за несколько дат для этого ученика', retry:'Повторить анкету', export:'Скачать CSV', filter:'Фильтр', qr:'QR-код для ученика', qrSub:'Этот код открывает страницу входа ученика.', back:'Назад', records:'записей', showAll:'Показать все', number:'Вопрос', secure:'Безопасная среда', loading:'Загрузка…', noteUnavailable:'Для записи действий специалистов необходима поддержка API.' },
 en: { home:'Home', overview:'Overview', survey:'Survey', admin:'Administrator', teacher:'Teacher', psychologist:'Psychologist', student:'Student', welcome:'Safer schools. Brighter futures.', welcomeSub:'A space to monitor and support students’ digital safety.', selectRole:'Open workspace', login:'Sign in', enter:'Continue', school:'School', class:'Class', id:'ID', password:'Password', user:'Username', choose:'Select', fill:'Please complete all fields', incorrect:'Incorrect username or password', surveyTitle:'Digital safety survey', surveySub:'Your answers will be reviewed carefully. Answer based on your own experience.', complaint:'Anything else you would like to share?', no:'No', sometimes:'Sometimes', yes:'Yes', submit:'Submit responses', sending:'Submitting…', saved:'Responses saved', result:'Result', risk:'Risk level', score:'Risk score', dashboard:'Monitoring dashboard', dashSub:'Student safety indicators', refresh:'Refresh', total:'Total surveys', high:'High risk', medium:'Medium risk', low:'Low risk', distribution:'Risk distribution', results:'Survey results', search:'Search student ID or school', all:'All levels', date:'Date', status:'Status', noResults:'No results found', apiError:'Could not load data. Please try again later.', work:'Work with student', workSub:'Select a student to review their support timeline', selectStudent:'Select a student from the results table', detected:'Risk detected', psychWork:'Psychologist work', teacherWork:'Homeroom teacher work', followUp:'Follow-up', current:'Current status', pending:'No data', specialist:'Responsible specialist', note:'Note', history:'Student progress', historyEmpty:'No results across multiple dates for this student yet', retry:'Retake survey', export:'Download CSV', filter:'Filter', qr:'Student QR code', qrSub:'This code opens the student sign-in page.', back:'Back', records:'records', showAll:'Show all', number:'Question', secure:'Safer learning', loading:'Loading…', noteUnavailable:'Recording specialist actions requires API support.' }
} as const;
export function riskBucket(value: unknown): 'high'|'medium'|'low'|'unknown' {
 const v=String(value ?? '').toLowerCase();
 if (['high','жоғары','высокий'].some(x=>v.includes(x))) return 'high';
 if (['medium','орта','средний'].some(x=>v.includes(x))) return 'medium';
 if (['low','safe','төмен','қауіпсіз','низкий','безопасно'].some(x=>v.includes(x))) return 'low';
 return 'unknown';
}
export const valueText = (v:unknown) => v == null || v === '' ? '—' : String(v);
